Add patch to update a vendorized dep, fixes a FTBFS against Go 1.14
go.etcd.io/bbolt needs to be updated to version 1.3.4 in order to fix a
the following error against Go 1.14:

fatal error: checkptr: unsafe pointer conversion

This patch was backported from the upstream master branch, so it should
be removed in the next upstream release.